feat: add user metadata
cryptlex/lexactivator-rust pull request #19
Opened 2024-08-28 07:23 UTC by muneebkq

add metadata to user license payload

2024-09-06 13:28 UTC, ahmad-kemsan commented on src/extern_functions.rs
> +    pub fn SetProductFile(filePath: cstrtype!()) -> c_int;
@muneebkq Remove this function, as we have deprecated SetProductFile(), so we will not include it in our rust wrapper.

2024-09-06 13:34 UTC, ahmad-kemsan commented on src/lib.rs
> +pub fn set_cache_mode(mode: bool) -> c_uint {
@muneebkq Please follow the Result return pattern for set_cache_mode().

2024-09-06 13:35 UTC, ahmad-kemsan requested changes
Please check the comments

2024-09-06 13:36 UTC, ahmad-kemsan commented
@muneebkq To fix the windows build error, update the version of LexActivator to 3.30.0 in download.sh. It should fix the issue.

2024-09-06 13:57 UTC, muneebkq commented on src/lib.rs
> +pub fn set_cache_mode(mode: bool) -> c_uint {
Jsdoc?

2024-09-06 14:34 UTC, muneebkq commented on src/extern_functions.rs
> +    pub fn SetProductFile(filePath: cstrtype!()) -> c_int;
removed

2024-09-06 14:35 UTC, muneebkq commented on src/lib.rs
> +pub fn set_cache_mode(mode: bool) -> c_uint {
result pattern followed

2024-09-10 03:53 UTC, ahmad-kemsan commented on src/lib.rs
> +pub fn set_app_version(app_version: String) -> Result<(), LexActivatorError> {
@muneebkq There is no need for adding set_app_version(). This function has been deprecated as we already have the set_release_version().

2024-09-12 12:55 UTC, ahmad-kemsan commented on src/extern_functions.rs
> +    pub fn SetCacheMode(mode: c_int) -> c_int;
@muneebkq SetCacheMode() take uint as an arg, please refer to https://github.com/cryptlex/lexactivator-c/blob/master/examples/LexActivator.h#L460

2024-09-12 12:55 UTC, ahmad-kemsan requested changes
Please check the comments

2024-09-19 12:02 UTC, ahmad-kemsan approved these changes

2024-09-19 12:02 UTC, merged